spring:
  profiles:
    active: dev
    include: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: 'false'
        show_sql: 'false'
    hibernate:
      ddl-auto: update